enum statesModel {
  AC = "AC",
  AL = "AL",
  AM = "AM",
  AP = "AP",
  BA = "BA",
  CE = "CE",
  DF = "DF",
  ES = "ES",
  GO = "GO",
  MA = "MA",
  MG = "MG",
  MS = "MS",
  MT = "MT",
  PA = "PA",
  PB = "PB",
  PE = "PE",
  PI = "PI",
  PR = "PR",
  RJ = "RJ",
  RN = "RN",
  RO = "RO",
  RR = "RR",
  RS = "RS",
  SC = "SC",
  SE = "SE",
  SP = "SP",
  TO = "TO",
}

export const statedata: statesModel[] = [
  statesModel.AC,
  statesModel.AL,
  statesModel.AP,
  statesModel.AM,
  statesModel.BA,
  statesModel.CE,
  statesModel.DF,
  statesModel.ES,
  statesModel.GO,
  statesModel.MA,
  statesModel.MT,
  statesModel.MS,
  statesModel.MG,
  statesModel.PA,
  statesModel.PB,
  statesModel.PR,
  statesModel.PE,
  statesModel.PI,
  statesModel.RJ,
  statesModel.RN,
  statesModel.RS,
  statesModel.RO,
  statesModel.RR,
  statesModel.SC,
  statesModel.SP,
  statesModel.TO,
  statesModel.SE
]
